import Header from "components/Header";
import { TKey } from "interfaces";
import { Suspense } from "react";
import { Outlet } from "react-router-dom";
import Sidebar from "./Sidebar";
import { Helmet } from "react-helmet";

const Layout: React.FC = (): React.ReactElement => {
  return (
    <>
      <Helmet>
        <title>{"healomath"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Helmet>
      <Header />
      <Sidebar />

      <main className="main flex flex-col md:ms-72 md:flex-grow  transition-all duration-150 ease-in">
        <div className="p-4">
          <Suspense fallback={<h4>Loading...</h4>}>
            <Outlet />
          </Suspense>
        </div>
      </main>
    </>
  );
};

export default Layout;
